#!/usr/bin/env bash
# Bash Script to configure an NGINX server with a custom HTTP header
sudo apt-get update
sudo apt install nginx -y
sudo chown -R ubuntu /var/www/html
echo "Esto no es una pagina" > /var/www/html/404.html
echo "Hello World" > /var/www/html/index.html
replace="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=snehh-hXoY8;\n\t}\n"
replace2="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
replace3="\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "47i\ $replace3$replace$replace2" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
