#!/usr/bin/env bash
# makes nginx run as user Nginx
sudo pkill apache2
sudo chmod 644 /etc/Nginx/Nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo su Nginx -c "service Nginx start"
